---
# tasks file for msoffice

- name: Download MS Office from Google Drive
  ansible.builtin.get_url:
    url: "{{ package_url }}"
    dest: /Users/asterr/Downloads/Microsoft_Office_16.63.22070801_BusinessPro_Installer.pkg.tmp
    mode: u=rw,g=r,o=r
    # checksum: "{{ package_checksum }}"

- name: Install MS Office from pkg
  ansible.builtin.include_tasks: install.yml
  vars:
    appNames:
    - Microsoft Excel
    - Microsoft OneNote
    - Microsoft Outlook
    - Microsoft PowerPoint
    - Microsoft Word
    pkgFile: /Users/asterr/Downloads/Microsoft_Office_16.63.22070801_BusinessPro_Installer.pkg
