---
# tasks file for pyenv

- name: Create group for user
  ansible.builtin.group:
    name: "{{ ansible_env.USER }}"
    state: present
  become: true

- name: Add user to group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    append: true
    groups:
      - "{{ ansible_env.USER }}"
  become: true
