---
# tasks file for pulse

- name: Install gdown with pip
  # This is needed to download large files
  # from Google Drive
  ansible.builtin.pip:
    name: gdown

- name: Check downloaded file
  ansible.builtin.stat:
    path: "{{ package_file }}"
  register: pulse_package_file

- ansible.builtin.debug:
    msg: "{{pulse_package_file}}"

- name: Download Pulse from Google Drive
  ansible.builtin.command: "gdown --continue -O {{ package_file }} {{ pulse_url }}"
  args:
    creates: "{{ package_file }}"
  when: >
    not pulse_package_file.stat.exists or
    pulse_package_file.stat.checksum != package_checksum

- name: Install Pulse from DMG
  ansible.builtin.include_role:
    name: dmg-install
  vars:
    appName: Pulse Secure
    dmgURL: "file://{{ package_file }}"
